LEVEL_ONE = [
  ['cat', 'gato'],
  ['fish', 'pescado'],
  ['bird', 'pájaro'],
  ['cow', 'vaca'],
  ['sheep', 'oveja'],
  ['goat', 'cabra'],
  ['pig', 'cerdo'],
  ['mouse', 'ratón'],
  ['rat', 'rata'],
  ['horse', 'caballo'],
  ['wing', 'ala'],
  ['animal', 'animal'],
  ['train', 'entrenar'],
  ['aeroplane', 'avión'],
  ['car', 'automóvil'],
  ['truck', 'camión'],
  ['bicycle', 'bicicleta'],
  ['motorcycle', 'motocicleta'],
  ['bus', 'autobús'],
  ['boat', 'barco'],
  ['ship', 'enviar'],
  ['tire', 'neumático'],
  ['gasoline', 'gasolina'],
  ['engine', 'motor'],
  ['train ticket', 'boleto de tren'],
  ['transportation', 'transportación'],
  ['city', 'ciudad'],
  ['house', 'casa'],
  ['apartment', 'apartamento'],
  ['street/road', 'calle / carretera'],
  ['airport', 'aeropuerto'],
  ['train station', 'estación de tren'],
  ['bridge', 'puente'],
  ['hotel', 'hotel'],
  ['restaurant', 'restaurante'],
  ['farm', 'granja'],
  ['court', 'la Corte'],
  ['school', 'colegio'],
  ['office', 'oficina'],
  ['room', 'cuarto'],
  ['town', 'ciudad'],
  ['university', 'universidad'],
  ['club', 'club'],
  ['bar', 'bar'],
  ['park', 'parque'],
  ['camp', 'acampar'],
  ['store/shop', 'tienda'],
  ['theater', 'el teatro'],
  ['library', 'biblioteca'],
  ['hospital', 'hospital'],
  ['temple', 'templo'],
  ['church', 'Iglesia'],
  ['market', 'mercado'],
  ['country', 'país'],
  ['nation', 'nación'],
  ['state', 'estado'],
  ['province', 'provincia'],
  ['district', 'distrito'],
  ['building', 'edificio'],
  ['ground', 'suelo'],
  ['outer space', 'espacio exterior'],
  ['bank', 'banco'],
  ['location', 'localización'],
  ['United States of America', 'Estados Unidos de America'],
  ['Australia', 'Australia'],
  ['Thailand', 'Tailandia'],
  ['China', 'China'],
  ['United Kingdom', 'Reino Unido'],
  ['England', 'Inglaterra'],
  ['Spain', 'España'],
  ['Germany', 'Alemania'],
  ['France', 'Francia'],
  ['Middle East', 'medio Este'],
  ['hat', 'sombrero'],
  ['dress', 'vestido'],
  ['suit', 'traje'],
  ['skirt', 'falda'],
  ['shirt', 'camisa'],
  ['T-shirt', 'Camiseta'],
  ['pants', 'pantalones'],
  ['shoes', 'Zapatos'],
  ['pocket', 'bolsillo'],
  ['coat', 'capa'],
  ['stain', 'manchar'],
  ['socks', 'calcetines'],
  ['gloves', 'guantes'],
  ['necktie', 'corbata'],
  ['vest', 'chaleco'],
  ['scarf', 'bufanda'],
  ['clothing', 'ropa']
]
LEVEL_TWO = [
  ['red', 'rojo'],
  ['green', 'verde'],
  ['light blue', 'azul claro'],
  ['dark blue', 'azul oscuro'],
  ['yellow', 'amarillo'],
  ['brown', 'marrón'],
  ['pink', 'Rosa'],
  ['purple', 'morado'],
  ['silver', 'plata'],
  ['gold', 'oro'],
  ['orange', 'naranja'],
  ['black', 'negro'],
  ['white', 'blanco'],
  ['gray', 'gris'],
  ['colour', 'color'],
  ['son*', 'hijo*'],
  ['daughter*', 'hija*'],
  ['mother', 'madre'],
  ['father', 'padre'],
  ['parents', 'madre padre - padre'],
  ['baby', 'bebé'],
  ['man', 'hombre'],
  ['woman', 'mujer'],
  ['brother*', 'hermano*'],
  ['sister*', 'hermana*'],
  ['family', 'familia'],
  ['grandfather', 'abuelo'],
  ['grandmother', 'abuela'],
  ['husband*', 'esposo*'],
  ['wife*', 'esposa*'],
  ['king', 'Rey'],
  ['queen', 'reina'],
  ['president', 'presidente'],
  ['neighbor', 'vecino'],
  ['boy', 'chico'],
  ['girl', 'muchacha'],
  ['child boy', 'muchachos niño'],
  ['child girl', 'Chica niño'],
  ['adult man', 'hombre adulto'],
  ['adult woman', 'mujer adulta'],
  ['human', 'humano'],
  ['friend', 'amigo'],
  ['victim', 'víctima'],
  ['player', 'jugador'],
  ['fan', 'abanico'],
  ['crowd', 'multitud'],
  ['person', 'la persona'],
  ['Teacher', 'maestro'],
  ['student', 'estudiante'],
  ['lawyer', 'abogado'],
  ['doctor', 'doctor'],
  ['patient', 'paciente'],
  ['waiter', 'camarero'],
  ['secretary', 'secretario'],
  ['priest', 'sacerdote'],
  ['police', 'policía'],
  ['army', 'ejército'],
  ['soldier', 'soldado'],
  ['artist', 'artista'],
  ['engineer', 'ingeniero'],
  ['author', 'autor'],
  ['manager', 'gerente'],
  ['reporter', 'reportero'],
  ['actor', 'actor'],
  ['job', 'trabajo']
]
LEVEL_THREE = [
  ['religion', 'religión'],
  ['heaven', 'cielo'],
  ['hell', 'infierno'],
  ['god', 'Dios'],
  ['devil', 'diablo'],
  ['angel', 'ángel'],
  ['fairy', 'hada'],
  ['spirit', 'espíritu'],
  ['demon', 'demonio'],
  ['death', 'muerte'],
  ['medicine', 'medicina'],
  ['money', 'dinero'],
  ['dollar', 'dólar'],
  ['bill', 'cuenta'],
  ['marriage*', 'matrimonio*'],
  ['wedding*', 'boda*'],
  ['team', 'equipo'],
  ['ethnicity', 'etnicidad'],
  ['sexual intercourse', 'relaciones sexuales'],
  ['gender', 'género'],
  ['murder', 'asesinato'],
  ['prison', 'prisión'],
  ['technology', 'tecnología'],
  ['energy', 'energía'],
  ['war', 'guerra'],
  ['peace', 'paz'],
  ['attack', 'ataque'],
  ['democracy', 'democracia'],
  ['capitalism', 'capitalismo'],
  ['socialism', 'socialismo'],
  ['communism', 'comunismo'],
  ['dictator', 'dictador'],
  ['election', 'elección'],
  ['magazine', 'revista'],
  ['newspaper', 'periódico'],
  ['poison', 'veneno'],
  ['gun', 'pistola'],
  ['sport', 'deporte'],
  ['sport race', 'carrera deportiva'],
  ['exercise', 'ejercicio'],
  ['ball', 'bola'],
  ['game', 'juego'],
  ['price', 'precio'],
  ['contract', 'contrato'],
  ['drug', 'droga'],
  ['sign', 'señal'],
  ['science', 'ciencia'],
  ['God', 'Dios'],
  ['band', 'banda'],
  ['song', 'canción'],
  ['musical instrument', 'instrumento musical'],
  ['music', 'música'],
  ['painting', 'cuadro'],
  ['photography', 'fotografía'],
  ['movie', 'película'],
  ['art', 'arte'],
  ['coffee', 'café'],
  ['tea', 'té'],
  ['wine', 'Vino'],
  ['beer', 'cerveza'],
  ['juice', 'jugo'],
  ['water', 'agua'],
  ['milk', 'leche'],
  ['beverage', 'bebida'],
  ['egg', 'huevo'],
  ['cheese', 'queso'],
  ['bread', 'pan de molde'],
  ['soup', 'sopa'],
  ['cake', 'pastel'],
  ['chicken', 'pollo'],
  ['pork', 'cerdo'],
  ['beef', 'carne de vaca'],
  ['apple', 'manzana'],
  ['banana', 'plátano'],
  ['orange', 'naranja'],
  ['lemon', 'limón'],
  ['corn', 'maíz'],
  ['rice', 'arroz'],
  ['oil', 'aceite'],
  ['seed', 'semilla'],
  ['knife', 'cuchillo'],
  ['spoon', 'cuchara'],
  ['fork', 'tenedor'],
  ['plate', 'plato'],
  ['cup', 'taza'],
  ['breakfast', 'desayuno'],
  ['lunch', 'almuerzo'],
  ['dinner', 'cena'],
  ['sugar', 'azúcar'],
  ['salt', 'sal'],
  ['bottle', 'botella'],
  ['food', 'comida'],
  ['table', 'mesa'],
  ['chair', 'silla'],
  ['bed', 'cama'],
  ['dream', 'sueña'],
  ['window', 'ventana'],
  ['door', 'puerta'],
  ['bedroom', 'dormitorio'],
  ['kitchen', 'cocina'],
  ['bathroom', 'baño'],
  ['pencil', 'lápiz'],
  ['pen', 'pluma'],
  ['photograph', 'fotografía'],
  ['soap', 'jabón'],
  ['book', 'libro'],
  ['page', 'página'],
  ['key', 'clave'],
  ['paint', 'pintura'],
  ['letter', 'carta'],
  ['note', 'Nota'],
  ['wall', 'pared'],
  ['brick', 'ladrillo'],
  ['tile', 'azulejo'],
  ['wood', 'madera'],
  ['concrete', 'hormigón'],
  ['paper', 'papel'],
  ['floor', 'planta'],
  ['ceiling', 'techo'],
  ['roof', 'techo'],
  ['pool', 'piscina'],
  ['lock', 'bloquear'],
  ['telephone', 'teléfono'],
  ['garden', 'jardín'],
  ['yard', 'yarda'],
  ['needle', 'aguja'],
  ['bag', 'bolso'],
  ['box', 'encajonar'],
  ['gift', 'regalo'],
  ['card', 'tarjeta'],
  ['ring', 'anillo'],
  ['tool', 'herramienta'],
  ['clock', 'reloj'],
  ['lamp', 'lámpara'],
  ['fan', 'abanico'],
  ['cell phone', 'Teléfono móvil'],
  ['network', 'la red'],
  ['computer', 'computadora'],
  ['computer program', 'programa de computadora'],
  ['laptop', 'computadora portátil'],
  ['screen', 'pantalla'],
  ['camera', 'camara fotografica'],
  ['television', 'televisión'],
  ['internet', 'Internet'],
  ['download', 'descargar'],
  ['install', 'instalar'],
  ['wifi', 'Wi-Fi'],
  ['radio', 'radio'],
  ['head', 'cabeza'],
  ['fur', 'pelaje'],
  ['neck', 'cuello'],
  ['face', 'cara'],
  ['beard', 'barba'],
  ['hair', 'cabello'],
  ['eye', 'ojo'],
  ['mouth', 'boca'],
  ['lips', 'labios'],
  ['nose', 'nariz'],
  ['tooth', 'diente'],
  ['ear', 'oreja'],
  ['teardrop', 'lágrima'],
  ['tongue', 'lengua'],
  ['back', 'atrás'],
  ['toe', 'dedo del pie'],
  ['finger', 'dedo'],
  ['foot', 'pie'],
  ['hand', 'mano'],
  ['leg', 'pierna'],
  ['arm', 'brazo'],
  ['shoulder', 'hombro'],
  ['heart', 'corazón'],
  ['blood', 'sangre'],
  ['brain', 'cerebro'],
  ['knee', 'rodilla'],
  ['sweat', 'sudor'],
  ['disease', 'enfermedad'],
  ['bone', 'hueso'],
  ['voice', 'voz'],
  ['skin', 'piel'],
  ['fingernail', 'uña'],
  ['eyebrow', 'ceja'],
  ['eyelash', 'pestaña'],
  ['corpse', 'cadáver'],
  ['human body', 'cuerpo humano'],
  ['sea*', 'mar*'],
  ['ocean*', 'océano*'],
  ['river', 'río'],
  ['mountain', 'montaña'],
  ['rain', 'lluvia'],
  ['snow', 'nieve'],
  ['tree', 'árbol'],
  ['sun', 'sol'],
  ['moon', 'Luna'],
  ['world', 'mundo'],
  ['Earth', 'Tierra'],
  ['forest', 'bosque'],
  ['sky', 'cielo'],
  ['plant', 'planta'],
  ['wind', 'viento'],
  ['soil/earth', 'suelo / tierra'],
  ['flower', 'flor'],
  ['valley', 'Valle'],
  ['root', 'raíz'],
  ['lake', 'lago'],
  ['star', 'estrella'],
  ['grass', 'césped'],
  ['leaf', 'hoja'],
  ['air', 'aire'],
  ['sand', 'arena'],
  ['beach', 'playa'],
  ['wave', 'ola'],
  ['fire', 'fuego'],
  ['ice', 'hielo'],
  ['island', 'isla'],
  ['hill', 'colina'],
  ['heat', 'calor'],
  ['north', 'norte'],
  ['south', 'sur'],
  ['east', 'este'],
  ['west', 'Oeste'],
  ['northeast', 'nordeste'],
  ['northwest', 'noroeste'],
  ['southeast', 'sudeste'],
  ['southwest', 'suroeste'],
  ['north pole', 'Polo Norte'],
  ['south pole', 'Polo Sur'],
  ['nature', 'naturaleza'],
  ['glass', 'vaso'],
  ['metal', 'metal'],
  ['plastic', 'el plastico'],
  ['wood', 'madera'],
  ['stone', 'piedra'],
  ['diamond', 'diamante'],
  ['clay', 'arcilla'],
  ['dust', 'polvo'],
  ['gold', 'oro'],
  ['copper', 'cobre'],
  ['silver', 'plata'],
  ['material', 'material'],
  ['meter', 'metro'],
  ['centimeter', 'centímetro'],
  ['kilogram', 'kilogramo'],
  ['inch', 'pulgada'],
  ['foot', 'pie'],
  ['pound', 'libra'],
  ['half', 'mitad'],
  ['circle', 'círculo'],
  ['square', 'cuadrado'],
  ['temperature', 'la temperatura'],
  ['date', 'fecha'],
  ['weight', 'peso'],
  ['edge', 'borde'],
  ['corner', 'esquina'],
  ['map', 'mapa'],
  ['dot', 'punto'],
  ['consonant', 'consonante'],
  ['vowel', 'vocal'],
  ['light', 'luz'],
  ['sound', 'sonar'],
  ['yes', 'sí'],
  ['no', 'no'],
  ['piece', 'pieza'],
  ['pain', 'dolor'],
  ['injury', 'lesión'],
  ['hole', 'agujero'],
  ['image', 'imagen'],
  ['pattern', 'patrón'],
  ['noun', 'sustantivo'],
  ['verb', 'verbo'],
  ['adjective', 'adjetivo'],
  ['top', 'cima'],
  ['bottom', 'fondo'],
  ['side', 'lado'],
  ['front', 'frente'],
  ['back', 'atrás'],
  ['outside', 'afuera'],
  ['inside', 'adentro de'],
  ['up', 'arriba'],
  ['down', 'abajo'],
  ['left', 'izquierdo'],
  ['right', 'derecho'],
  ['straight', 'recto'],
  ['beside', 'junto a'],
  ['at', 'a'],
  ['direction', 'dirección'],
  ['Summer', 'El verano'],
  ['Spring', 'Primavera'],
  ['Winter', 'Invierno'],
  ['dry season', 'estación seca'],
  ['wet season', 'temporada húmeda'],
  ['hot season', 'temporada cálida'],
  ['Fall', 'Caer'],
  ['season', 'temporada'],
  ['zero', 'cero'],
  ['one', 'uno'],
  ['two', 'dos'],
  ['three', 'Tres'],
  ['four', 'cuatro'],
  ['five', 'cinco'],
  ['six', 'seis'],
  ['seven', 'siete'],
  ['eight', 'ocho'],
  ['nine', 'nueve'],
  ['ten', 'diez'],
  ['eleven', 'once'],
  ['twelve', 'doce'],
  ['thirteen', 'trece'],
  ['fourteen', 'catorce'],
  ['fifteen', 'fifiteen'],
  ['sixteen', 'dieciséis'],
  ['seventeen', 'diecisiete'],
  ['eighteen', 'Dieciocho'],
  ['nineteen', 'diecinueve'],
  ['twenty', '20'],
  ['twenty-one', 'veintiún'],
  ['twenty-two', 'Veintidós'],
  ['thirty', 'treinta'],
  ['thirty-one', 'treinta y uno'],
  ['thirty-two', 'treinta y dos'],
  ['forty', 'cuarenta'],
  ['forty-one', 'cuarenta y uno'],
  ['forty-two', 'cuarenta y dos'],
  ['fifty', 'cincuenta'],
  ['fifty-one', 'cincuenta y uno'],
  ['fifty-two', 'cincuenta y dos'],
  ['sixty', 'sesenta'],
  ['sixty-one', 'sesenta y uno'],
  ['sixty-two', 'sesenta y dos'],
  ['seventy', 'setenta'],
  ['seventy-one', 'setenta y uno'],
  ['seventy-two', 'setenta y dos'],
  ['eighty', 'ochenta'],
  ['eighty-one', 'ochenta y uno'],
  ['eighty-two', 'ochenta y dos'],
  ['ninety', 'noventa'],
  ['ninety-one', 'noventa y uno'],
  ['ninety-two', 'noventa y dos'],
  ['one hundred', 'cien'],
  ['one hundred and one', 'ciento uno'],
  ['one hundred and two', 'ciento dos'],
  ['one hundred and ten', 'ciento diez'],
  ['one hundred and eleven', 'Ciento once'],
  ['one thousand', 'mil'],
  ['one thousand and one', 'ciento uno'],
  ['ten thousand', 'diez mil'],
  ['one hundred thousand', 'cien mil'],
  ['one million', 'un millón'],
  ['one billion', 'se billioin'],
  ['first', 'primero'],
  ['second', 'segundo'],
  ['third', 'tercera'],
  ['fourth', 'cuarto'],
  ['fifth', 'quinto'],
  ['sixth', 'sexto'],
  ['January', 'enero'],
  ['February', 'febrero'],
  ['March', 'marzo'],
  ['April', 'abril'],
  ['May', 'Mayo'],
  ['June', 'junio'],
  ['July', 'julio'],
  ['August', 'agosto'],
  ['September', 'septiembre'],
  ['October', 'octubre'],
  ['November', 'noviembre'],
  ['December', 'diciembre'],
  ['Monday', 'lunes'],
  ['Tuesday', 'martes'],
  ['Wednesday', 'miércoles'],
  ['Thursday', 'jueves'],
  ['Friday', 'viernes'],
  ['Saturday', 'sábado'],
  ['Sunday', 'domingo'],
  ['year', 'año'],
  ['month', 'mes'],
  ['week', 'semana'],
  ['day', 'día'],
  ['hour', 'hora'],
  ['minute', 'minuto'],
  ['second', 'segundo'],
  ['morning', 'Mañana'],
  ['afternoon', 'tarde'],
  ['evening', 'anochecer'],
  ['night', 'noche'],
  ['time', 'hora'],
  ['to work', 'trabajar'],
  ['to play', 'jugar'],
  ['to walk', 'caminar'],
  ['to run', 'correr'],
  ['to drive', 'conducir'],
  ['to fly', 'para volar'],
  ['to swim', 'nadar'],
  ['to go', 'ir'],
  ['to stop', 'detener'],
  ['to follow', 'seguir'],
  ['to think', 'pensar'],
  ['to speak', 'hablar'],
  ['to say', 'decir'],
  ['to chat', 'para charlar'],
  ['to tell', 'decir'],
  ['to whisper', 'susurrar'],
  ['to yell', 'gritar'],
  ['to eat', 'comer'],
  ['to drink', 'beber'],
  ['to kill', 'matar'],
  ['to die', 'morir'],
  ['to win', 'ganar'],
  ['to lose', 'A perder'],
  ['to smile', 'sonreír'],
  ['to laugh', 'reír'],
  ['to cry', 'llorar'],
  ['to buy', 'Comprar'],
  ['to pay', 'pagar'],
  ['to sell', 'para vender'],
  ['to shoot a gun', 'para disparar un arma de fuego'],
  ['to learn', 'aprender'],
  ['to jump', 'saltar'],
  ['to smell', 'oler'],
  ['to hear sound', 'para escuchar el sonido'],
  ['to listen to music', 'escuchar música'],
  ['to taste', 'probar'],
  ['to touch', 'tocar'],
  ['to see a bird', 'para ver un pájaro'],
  ['to watch tv', 'ver la televisión'],
  ['to kiss', 'para besar'],
  ['to burn', 'para quemar'],
  ['to melt', 'para fundir'],
  ['to dig', 'cavar'],
  ['to explode', 'explotar'],
  ['to sit', 'sentarse'],
  ['to stand', 'reposar'],
  ['to love', 'amar'],
  ['to pass by', 'pasar por'],
  ['to cut', 'Para cortar'],
  ['to fight', 'pelear'],
  ['to lie down', 'tumbarse'],
  ['to dance', 'bailar'],
  ['to sleep', 'dormir'],
  ['to wake up', 'Para despertar'],
  ['to sing', 'cantar'],
  ['to count', 'para contar'],
  ['to marry', 'casarse'],
  ['to pray', 'a orar'],
  ['to win', 'ganar'],
  ['to lose', 'A perder'],
  ['to mix/stir', 'mezclar / revuelo'],
  ['to bend', 'para doblar'],
  ['to wash', 'lavar'],
  ['to cook', 'cocinar'],
  ['to open', 'abrir'],
  ['to close', 'cerrar'],
  ['to write', 'escribir'],
  ['to call', 'llamar'],
  ['to turn', 'girar'],
  ['to build', 'para construir'],
  ['to teach', 'enseñar'],
  ['to grow', 'crecer'],
  ['to draw', 'dibujar'],
  ['to feed', 'Para alimentar'],
  ['to catch', 'atrapar'],
  ['to throw', 'lanzar'],
  ['to clean', 'limpiar'],
  ['to find', 'encontrar'],
  ['to fall', 'caer'],
  ['to stumble', 'tropezar'],
  ['to fall in love', 'para enamorarse'],
  ['to push', 'para empujar'],
  ['to pull', 'tirar'],
  ['to carry', 'llevar'],
  ['to break', 'romper'],
  ['to wear', 'llevar'],
  ['to hang', 'colgar'],
  ['to shake', 'agitar'],
  ['to sign', 'para firmar'],
  ['to beat', 'vencer'],
  ['to lift', 'levantar'],
  ['long', 'largo'],
  ['short', 'corto y largo'],
  ['tall', 'alto'],
  ['short (vs tall)', 'corto (vs altura)'],
  ['wide', 'amplio'],
  ['narrow', 'angostas'],
  ['big - large', 'Muy grande'],
  ['small - little', 'pequeña - pequeña'],
  ['slow', 'lento'],
  ['fast', 'ayunar'],
  ['hot', 'caliente'],
  ['cold', 'frío'],
  ['warm', 'calentar'],
  ['cool', 'guay'],
  ['new', 'nuevo'],
  ['old - new', 'viejo nuevo'],
  ['young', 'joven'],
  ['young and old', 'joven y viejo'],
  ['good', 'bien'],
  ['bad', 'malo'],
  ['wet', 'mojado'],
  ['dry', 'seco'],
  ['sick', 'enfermos'],
  ['healthy', 'saludable'],
  ['loud', 'ruidoso'],
  ['quiet', 'tranquilo'],
  ['happy', 'feliz'],
  ['sad', 'triste'],
  ['beautiful', 'hermosa'],
  ['ugly', 'feo'],
  ['cute', 'linda'],
  ['deaf', 'sordo'],
  ['blind', 'ciego'],
  ['nice', 'bonito'],
  ['mean', 'media'],
  ['rich', 'Rico'],
  ['poor', 'pobre'],
  ['thick', 'grueso'],
  ['thin', 'delgada'],
  ['expensive', 'caro'],
  ['cheap', 'barato'],
  ['flat', 'llano'],
  ['curved', 'curvo'],
  ['male', 'masculino'],
  ['female', 'hembra'],
  ['tight', 'ajustado'],
  ['loose', 'suelto'],
  ['high', 'alto'],
  ['low', 'bajo'],
  ['soft', 'suave'],
  ['hard', 'difícil'],
  ['deep', 'profundo'],
  ['shallow', 'superficial'],
  ['clean', 'limpiar'],
  ['dirty', 'sucio'],
  ['strong', 'fuerte'],
  ['weak', 'débiles'],
  ['dead', 'muerto'],
  ['alive', 'viva'],
  ['heavy', 'pesado'],
  ['lightweight', 'ligero'],
  ['dark', 'oscuro'],
  ['light color', 'color claro'],
  ['nuclear', 'nuclear'],
  ['famous', 'famoso'],
  ['I', 'yo'],
  ['you', 'usted'],
  ['he', 'él'],
  ['she', 'ella'],
  ['it', 'ello'],
  ['we', 'nosotros'],
  ['all of you', 'Todos ustedes'],
  ['they', 'ellos'],
  ['What?', '¿Qué?'],
  ['Which?', '¿Cual?'],
  ['Where?', '¿Dónde?'],
  ['Who?', '¿OMS?'],
  ['Why?', '¿Por qué?'],
  ['How?', '¿Cómo?'],
  ['How Much?', '¿Cuánto cuesta?'],
  ['How Many?', '¿Cuántos?']
]